-- History triggers (P29, D122). Generated by `make audit-triggers`: do not edit by hand
DROP TRIGGER IF EXISTS "aud_ins_exp_daily_expenses";
DROP TRIGGER IF EXISTS "aud_upd_exp_daily_expenses";
DROP TRIGGER IF EXISTS "aud_del_exp_daily_expenses";
DROP TRIGGER IF EXISTS "aud_ins_exp_fixed_costs";
DROP TRIGGER IF EXISTS "aud_upd_exp_fixed_costs";
DROP TRIGGER IF EXISTS "aud_del_exp_fixed_costs";
DROP TRIGGER IF EXISTS "aud_ins_exp_subscriptions";
DROP TRIGGER IF EXISTS "aud_upd_exp_subscriptions";
DROP TRIGGER IF EXISTS "aud_del_exp_subscriptions";
DROP TRIGGER IF EXISTS "aud_ins_exp_credit_card_expenses";
DROP TRIGGER IF EXISTS "aud_upd_exp_credit_card_expenses";
DROP TRIGGER IF EXISTS "aud_del_exp_credit_card_expenses";
DROP TRIGGER IF EXISTS "aud_ins_exp_recurring_expenses";
DROP TRIGGER IF EXISTS "aud_upd_exp_recurring_expenses";
DROP TRIGGER IF EXISTS "aud_del_exp_recurring_expenses";
DROP TRIGGER IF EXISTS "aud_ins_exp_debts";
DROP TRIGGER IF EXISTS "aud_upd_exp_debts";
DROP TRIGGER IF EXISTS "aud_del_exp_debts";
DROP TRIGGER IF EXISTS "aud_ins_exp_debt_payments";
DROP TRIGGER IF EXISTS "aud_upd_exp_debt_payments";
DROP TRIGGER IF EXISTS "aud_del_exp_debt_payments";
DROP TRIGGER IF EXISTS "aud_ins_exp_commitments";
DROP TRIGGER IF EXISTS "aud_upd_exp_commitments";
DROP TRIGGER IF EXISTS "aud_del_exp_commitments";
DROP TRIGGER IF EXISTS "aud_ins_exp_contributions";
DROP TRIGGER IF EXISTS "aud_upd_exp_contributions";
DROP TRIGGER IF EXISTS "aud_del_exp_contributions";
DROP TRIGGER IF EXISTS "aud_ins_bud_monthly_budgets";
DROP TRIGGER IF EXISTS "aud_upd_bud_monthly_budgets";
DROP TRIGGER IF EXISTS "aud_del_bud_monthly_budgets";
DROP TRIGGER IF EXISTS "aud_ins_bud_budget_groups";
DROP TRIGGER IF EXISTS "aud_upd_bud_budget_groups";
DROP TRIGGER IF EXISTS "aud_del_bud_budget_groups";
DROP TRIGGER IF EXISTS "aud_ins_bud_category_budgets";
DROP TRIGGER IF EXISTS "aud_upd_bud_category_budgets";
DROP TRIGGER IF EXISTS "aud_del_bud_category_budgets";
DROP TRIGGER IF EXISTS "aud_ins_bud_incomes";
DROP TRIGGER IF EXISTS "aud_upd_bud_incomes";
DROP TRIGGER IF EXISTS "aud_del_bud_incomes";
DROP TRIGGER IF EXISTS "aud_ins_bud_settings";
DROP TRIGGER IF EXISTS "aud_upd_bud_settings";
DROP TRIGGER IF EXISTS "aud_del_bud_settings";
DROP TRIGGER IF EXISTS "aud_ins_cat_people";
DROP TRIGGER IF EXISTS "aud_upd_cat_people";
DROP TRIGGER IF EXISTS "aud_del_cat_people";
DROP TRIGGER IF EXISTS "aud_ins_cat_payment_methods";
DROP TRIGGER IF EXISTS "aud_upd_cat_payment_methods";
DROP TRIGGER IF EXISTS "aud_del_cat_payment_methods";
DROP TRIGGER IF EXISTS "aud_ins_cat_card_holders";
DROP TRIGGER IF EXISTS "aud_upd_cat_card_holders";
DROP TRIGGER IF EXISTS "aud_del_cat_card_holders";
DROP TRIGGER IF EXISTS "aud_ins_cat_categories";
DROP TRIGGER IF EXISTS "aud_upd_cat_categories";
DROP TRIGGER IF EXISTS "aud_del_cat_categories";
DROP TRIGGER IF EXISTS "aud_ins_ntf_settings";
DROP TRIGGER IF EXISTS "aud_upd_ntf_settings";
DROP TRIGGER IF EXISTS "aud_del_ntf_settings";

CREATE TRIGGER "aud_ins_exp_daily_expenses" AFTER INSERT ON "exp_daily_expenses"
BEGIN
  INSERT INTO "aud_changes" ("id", "entity", "entityId", "action", "changes", "source", "actorId", "batchId", "userId", "createdAt")
  SELECT lower(hex(randomblob(12))), 'exp_daily_expenses', NEW."id", 'create', json_object('id', NEW."id", 'description', NEW."description", 'amount', NEW."amount", 'othersShare', NEW."othersShare", 'currency', NEW."currency", 'exchangeRate', NEW."exchangeRate", 'amountInPen', NEW."amountInPen", 'expenseType', NEW."expenseType", 'spentAt', NEW."spentAt", 'personId', NEW."personId", 'paymentMethodId', NEW."paymentMethodId", 'categoryId', NEW."categoryId", 'merchant', NEW."merchant", 'operationNumber', NEW."operationNumber", 'notes', NEW."notes", 'draftId', NEW."draftId", 'createdAt', NEW."createdAt", 'updatedAt', NEW."updatedAt", 'userId', NEW."userId", 'tripId', NEW."tripId"), COALESCE(c."source", 'cli'), c."actorId", c."batchId", NEW."userId", strftime('%Y-%m-%dT%H:%M:%f', 'now') || '+00:00'
  FROM (SELECT 1) LEFT JOIN "aud_context" c ON c."id" = 1
  WHERE COALESCE(c."source", 'cli') <> 'import';
END;

CREATE TRIGGER "aud_upd_exp_daily_expenses" AFTER UPDATE ON "exp_daily_expenses"
BEGIN
  INSERT INTO "aud_changes" ("id", "entity", "entityId", "action", "changes", "source", "actorId", "batchId", "userId", "createdAt")
  SELECT lower(hex(randomblob(12))), 'exp_daily_expenses', NEW."id", 'update', diff."changes", COALESCE(c."source", 'cli'), c."actorId", c."batchId", NEW."userId", strftime('%Y-%m-%dT%H:%M:%f', 'now') || '+00:00'
  FROM (SELECT json_group_object("k", json_array("o", "n")) AS "changes", COUNT(*) AS "total" FROM (
      SELECT 'id' AS "k", OLD."id" AS "o", NEW."id" AS "n"
      UNION ALL SELECT 'description', OLD."description", NEW."description"
      UNION ALL SELECT 'amount', OLD."amount", NEW."amount"
      UNION ALL SELECT 'othersShare', OLD."othersShare", NEW."othersShare"
      UNION ALL SELECT 'currency', OLD."currency", NEW."currency"
      UNION ALL SELECT 'exchangeRate', OLD."exchangeRate", NEW."exchangeRate"
      UNION ALL SELECT 'amountInPen', OLD."amountInPen", NEW."amountInPen"
      UNION ALL SELECT 'expenseType', OLD."expenseType", NEW."expenseType"
      UNION ALL SELECT 'spentAt', OLD."spentAt", NEW."spentAt"
      UNION ALL SELECT 'personId', OLD."personId", NEW."personId"
      UNION ALL SELECT 'paymentMethodId', OLD."paymentMethodId", NEW."paymentMethodId"
      UNION ALL SELECT 'categoryId', OLD."categoryId", NEW."categoryId"
      UNION ALL SELECT 'merchant', OLD."merchant", NEW."merchant"
      UNION ALL SELECT 'operationNumber', OLD."operationNumber", NEW."operationNumber"
      UNION ALL SELECT 'notes', OLD."notes", NEW."notes"
      UNION ALL SELECT 'draftId', OLD."draftId", NEW."draftId"
      UNION ALL SELECT 'createdAt', OLD."createdAt", NEW."createdAt"
      UNION ALL SELECT 'userId', OLD."userId", NEW."userId"
      UNION ALL SELECT 'tripId', OLD."tripId", NEW."tripId"
    ) WHERE "o" IS NOT "n") diff
  LEFT JOIN "aud_context" c ON c."id" = 1
  WHERE diff."total" > 0 AND COALESCE(c."source", 'cli') <> 'import';
END;

CREATE TRIGGER "aud_del_exp_daily_expenses" AFTER DELETE ON "exp_daily_expenses"
BEGIN
  INSERT INTO "aud_changes" ("id", "entity", "entityId", "action", "changes", "source", "actorId", "batchId", "userId", "createdAt")
  SELECT lower(hex(randomblob(12))), 'exp_daily_expenses', OLD."id", 'delete', json_object('id', OLD."id", 'description', OLD."description", 'amount', OLD."amount", 'othersShare', OLD."othersShare", 'currency', OLD."currency", 'exchangeRate', OLD."exchangeRate", 'amountInPen', OLD."amountInPen", 'expenseType', OLD."expenseType", 'spentAt', OLD."spentAt", 'personId', OLD."personId", 'paymentMethodId', OLD."paymentMethodId", 'categoryId', OLD."categoryId", 'merchant', OLD."merchant", 'operationNumber', OLD."operationNumber", 'notes', OLD."notes", 'draftId', OLD."draftId", 'createdAt', OLD."createdAt", 'updatedAt', OLD."updatedAt", 'userId', OLD."userId", 'tripId', OLD."tripId"), COALESCE(c."source", 'cli'), c."actorId", c."batchId", OLD."userId", strftime('%Y-%m-%dT%H:%M:%f', 'now') || '+00:00'
  FROM (SELECT 1) LEFT JOIN "aud_context" c ON c."id" = 1
  WHERE COALESCE(c."source", 'cli') <> 'import';
END;

CREATE TRIGGER "aud_ins_exp_fixed_costs" AFTER INSERT ON "exp_fixed_costs"
BEGIN
  INSERT INTO "aud_changes" ("id", "entity", "entityId", "action", "changes", "source", "actorId", "batchId", "userId", "createdAt")
  SELECT lower(hex(randomblob(12))), 'exp_fixed_costs', NEW."id", 'create', json_object('id', NEW."id", 'description', NEW."description", 'amount', NEW."amount", 'othersShare', NEW."othersShare", 'currency', NEW."currency", 'exchangeRate', NEW."exchangeRate", 'amountInPen', NEW."amountInPen", 'expenseType', NEW."expenseType", 'paymentStatus', NEW."paymentStatus", 'personId', NEW."personId", 'categoryId', NEW."categoryId", 'paymentMethodId', NEW."paymentMethodId", 'installment', NEW."installment", 'paymentMonth', NEW."paymentMonth", 'paymentYear', NEW."paymentYear", 'paymentDate', NEW."paymentDate", 'dueDate', NEW."dueDate", 'attentionDate', NEW."attentionDate", 'notes', NEW."notes", 'draftId', NEW."draftId", 'createdAt', NEW."createdAt", 'updatedAt', NEW."updatedAt", 'importKey', NEW."importKey", 'commitmentId', NEW."commitmentId", 'userId', NEW."userId"), COALESCE(c."source", 'cli'), c."actorId", c."batchId", NEW."userId", strftime('%Y-%m-%dT%H:%M:%f', 'now') || '+00:00'
  FROM (SELECT 1) LEFT JOIN "aud_context" c ON c."id" = 1
  WHERE COALESCE(c."source", 'cli') <> 'import';
END;

CREATE TRIGGER "aud_upd_exp_fixed_costs" AFTER UPDATE ON "exp_fixed_costs"
BEGIN
  INSERT INTO "aud_changes" ("id", "entity", "entityId", "action", "changes", "source", "actorId", "batchId", "userId", "createdAt")
  SELECT lower(hex(randomblob(12))), 'exp_fixed_costs', NEW."id", 'update', diff."changes", COALESCE(c."source", 'cli'), c."actorId", c."batchId", NEW."userId", strftime('%Y-%m-%dT%H:%M:%f', 'now') || '+00:00'
  FROM (SELECT json_group_object("k", json_array("o", "n")) AS "changes", COUNT(*) AS "total" FROM (
      SELECT 'id' AS "k", OLD."id" AS "o", NEW."id" AS "n"
      UNION ALL SELECT 'description', OLD."description", NEW."description"
      UNION ALL SELECT 'amount', OLD."amount", NEW."amount"
      UNION ALL SELECT 'othersShare', OLD."othersShare", NEW."othersShare"
      UNION ALL SELECT 'currency', OLD."currency", NEW."currency"
      UNION ALL SELECT 'exchangeRate', OLD."exchangeRate", NEW."exchangeRate"
      UNION ALL SELECT 'amountInPen', OLD."amountInPen", NEW."amountInPen"
      UNION ALL SELECT 'expenseType', OLD."expenseType", NEW."expenseType"
      UNION ALL SELECT 'paymentStatus', OLD."paymentStatus", NEW."paymentStatus"
      UNION ALL SELECT 'personId', OLD."personId", NEW."personId"
      UNION ALL SELECT 'categoryId', OLD."categoryId", NEW."categoryId"
      UNION ALL SELECT 'paymentMethodId', OLD."paymentMethodId", NEW."paymentMethodId"
      UNION ALL SELECT 'installment', OLD."installment", NEW."installment"
      UNION ALL SELECT 'paymentMonth', OLD."paymentMonth", NEW."paymentMonth"
      UNION ALL SELECT 'paymentYear', OLD."paymentYear", NEW."paymentYear"
      UNION ALL SELECT 'paymentDate', OLD."paymentDate", NEW."paymentDate"
      UNION ALL SELECT 'dueDate', OLD."dueDate", NEW."dueDate"
      UNION ALL SELECT 'attentionDate', OLD."attentionDate", NEW."attentionDate"
      UNION ALL SELECT 'notes', OLD."notes", NEW."notes"
      UNION ALL SELECT 'draftId', OLD."draftId", NEW."draftId"
      UNION ALL SELECT 'createdAt', OLD."createdAt", NEW."createdAt"
      UNION ALL SELECT 'importKey', OLD."importKey", NEW."importKey"
      UNION ALL SELECT 'commitmentId', OLD."commitmentId", NEW."commitmentId"
      UNION ALL SELECT 'userId', OLD."userId", NEW."userId"
    ) WHERE "o" IS NOT "n") diff
  LEFT JOIN "aud_context" c ON c."id" = 1
  WHERE diff."total" > 0 AND COALESCE(c."source", 'cli') <> 'import';
END;

CREATE TRIGGER "aud_del_exp_fixed_costs" AFTER DELETE ON "exp_fixed_costs"
BEGIN
  INSERT INTO "aud_changes" ("id", "entity", "entityId", "action", "changes", "source", "actorId", "batchId", "userId", "createdAt")
  SELECT lower(hex(randomblob(12))), 'exp_fixed_costs', OLD."id", 'delete', json_object('id', OLD."id", 'description', OLD."description", 'amount', OLD."amount", 'othersShare', OLD."othersShare", 'currency', OLD."currency", 'exchangeRate', OLD."exchangeRate", 'amountInPen', OLD."amountInPen", 'expenseType', OLD."expenseType", 'paymentStatus', OLD."paymentStatus", 'personId', OLD."personId", 'categoryId', OLD."categoryId", 'paymentMethodId', OLD."paymentMethodId", 'installment', OLD."installment", 'paymentMonth', OLD."paymentMonth", 'paymentYear', OLD."paymentYear", 'paymentDate', OLD."paymentDate", 'dueDate', OLD."dueDate", 'attentionDate', OLD."attentionDate", 'notes', OLD."notes", 'draftId', OLD."draftId", 'createdAt', OLD."createdAt", 'updatedAt', OLD."updatedAt", 'importKey', OLD."importKey", 'commitmentId', OLD."commitmentId", 'userId', OLD."userId"), COALESCE(c."source", 'cli'), c."actorId", c."batchId", OLD."userId", strftime('%Y-%m-%dT%H:%M:%f', 'now') || '+00:00'
  FROM (SELECT 1) LEFT JOIN "aud_context" c ON c."id" = 1
  WHERE COALESCE(c."source", 'cli') <> 'import';
END;

CREATE TRIGGER "aud_ins_exp_subscriptions" AFTER INSERT ON "exp_subscriptions"
BEGIN
  INSERT INTO "aud_changes" ("id", "entity", "entityId", "action", "changes", "source", "actorId", "batchId", "userId", "createdAt")
  SELECT lower(hex(randomblob(12))), 'exp_subscriptions', NEW."id", 'create', json_object('id', NEW."id", 'description', NEW."description", 'amount', NEW."amount", 'othersShare', NEW."othersShare", 'currency', NEW."currency", 'exchangeRate', NEW."exchangeRate", 'amountInPen', NEW."amountInPen", 'expenseType', NEW."expenseType", 'paymentStatus', NEW."paymentStatus", 'period', NEW."period", 'personId', NEW."personId", 'categoryId', NEW."categoryId", 'paymentMethodId', NEW."paymentMethodId", 'installment', NEW."installment", 'paymentMonth', NEW."paymentMonth", 'paymentYear', NEW."paymentYear", 'paymentDate', NEW."paymentDate", 'dueDate', NEW."dueDate", 'notes', NEW."notes", 'draftId', NEW."draftId", 'createdAt', NEW."createdAt", 'updatedAt', NEW."updatedAt", 'importKey', NEW."importKey", 'kind', NEW."kind", 'supplyNumber', NEW."supplyNumber", 'userId', NEW."userId"), COALESCE(c."source", 'cli'), c."actorId", c."batchId", NEW."userId", strftime('%Y-%m-%dT%H:%M:%f', 'now') || '+00:00'
  FROM (SELECT 1) LEFT JOIN "aud_context" c ON c."id" = 1
  WHERE COALESCE(c."source", 'cli') <> 'import';
END;

CREATE TRIGGER "aud_upd_exp_subscriptions" AFTER UPDATE ON "exp_subscriptions"
BEGIN
  INSERT INTO "aud_changes" ("id", "entity", "entityId", "action", "changes", "source", "actorId", "batchId", "userId", "createdAt")
  SELECT lower(hex(randomblob(12))), 'exp_subscriptions', NEW."id", 'update', diff."changes", COALESCE(c."source", 'cli'), c."actorId", c."batchId", NEW."userId", strftime('%Y-%m-%dT%H:%M:%f', 'now') || '+00:00'
  FROM (SELECT json_group_object("k", json_array("o", "n")) AS "changes", COUNT(*) AS "total" FROM (
      SELECT 'id' AS "k", OLD."id" AS "o", NEW."id" AS "n"
      UNION ALL SELECT 'description', OLD."description", NEW."description"
      UNION ALL SELECT 'amount', OLD."amount", NEW."amount"
      UNION ALL SELECT 'othersShare', OLD."othersShare", NEW."othersShare"
      UNION ALL SELECT 'currency', OLD."currency", NEW."currency"
      UNION ALL SELECT 'exchangeRate', OLD."exchangeRate", NEW."exchangeRate"
      UNION ALL SELECT 'amountInPen', OLD."amountInPen", NEW."amountInPen"
      UNION ALL SELECT 'expenseType', OLD."expenseType", NEW."expenseType"
      UNION ALL SELECT 'paymentStatus', OLD."paymentStatus", NEW."paymentStatus"
      UNION ALL SELECT 'period', OLD."period", NEW."period"
      UNION ALL SELECT 'personId', OLD."personId", NEW."personId"
      UNION ALL SELECT 'categoryId', OLD."categoryId", NEW."categoryId"
      UNION ALL SELECT 'paymentMethodId', OLD."paymentMethodId", NEW."paymentMethodId"
      UNION ALL SELECT 'installment', OLD."installment", NEW."installment"
      UNION ALL SELECT 'paymentMonth', OLD."paymentMonth", NEW."paymentMonth"
      UNION ALL SELECT 'paymentYear', OLD."paymentYear", NEW."paymentYear"
      UNION ALL SELECT 'paymentDate', OLD."paymentDate", NEW."paymentDate"
      UNION ALL SELECT 'dueDate', OLD."dueDate", NEW."dueDate"
      UNION ALL SELECT 'notes', OLD."notes", NEW."notes"
      UNION ALL SELECT 'draftId', OLD."draftId", NEW."draftId"
      UNION ALL SELECT 'createdAt', OLD."createdAt", NEW."createdAt"
      UNION ALL SELECT 'importKey', OLD."importKey", NEW."importKey"
      UNION ALL SELECT 'kind', OLD."kind", NEW."kind"
      UNION ALL SELECT 'supplyNumber', OLD."supplyNumber", NEW."supplyNumber"
      UNION ALL SELECT 'userId', OLD."userId", NEW."userId"
    ) WHERE "o" IS NOT "n") diff
  LEFT JOIN "aud_context" c ON c."id" = 1
  WHERE diff."total" > 0 AND COALESCE(c."source", 'cli') <> 'import';
END;

CREATE TRIGGER "aud_del_exp_subscriptions" AFTER DELETE ON "exp_subscriptions"
BEGIN
  INSERT INTO "aud_changes" ("id", "entity", "entityId", "action", "changes", "source", "actorId", "batchId", "userId", "createdAt")
  SELECT lower(hex(randomblob(12))), 'exp_subscriptions', OLD."id", 'delete', json_object('id', OLD."id", 'description', OLD."description", 'amount', OLD."amount", 'othersShare', OLD."othersShare", 'currency', OLD."currency", 'exchangeRate', OLD."exchangeRate", 'amountInPen', OLD."amountInPen", 'expenseType', OLD."expenseType", 'paymentStatus', OLD."paymentStatus", 'period', OLD."period", 'personId', OLD."personId", 'categoryId', OLD."categoryId", 'paymentMethodId', OLD."paymentMethodId", 'installment', OLD."installment", 'paymentMonth', OLD."paymentMonth", 'paymentYear', OLD."paymentYear", 'paymentDate', OLD."paymentDate", 'dueDate', OLD."dueDate", 'notes', OLD."notes", 'draftId', OLD."draftId", 'createdAt', OLD."createdAt", 'updatedAt', OLD."updatedAt", 'importKey', OLD."importKey", 'kind', OLD."kind", 'supplyNumber', OLD."supplyNumber", 'userId', OLD."userId"), COALESCE(c."source", 'cli'), c."actorId", c."batchId", OLD."userId", strftime('%Y-%m-%dT%H:%M:%f', 'now') || '+00:00'
  FROM (SELECT 1) LEFT JOIN "aud_context" c ON c."id" = 1
  WHERE COALESCE(c."source", 'cli') <> 'import';
END;

CREATE TRIGGER "aud_ins_exp_credit_card_expenses" AFTER INSERT ON "exp_credit_card_expenses"
BEGIN
  INSERT INTO "aud_changes" ("id", "entity", "entityId", "action", "changes", "source", "actorId", "batchId", "userId", "createdAt")
  SELECT lower(hex(randomblob(12))), 'exp_credit_card_expenses', NEW."id", 'create', json_object('id', NEW."id", 'description', NEW."description", 'amount', NEW."amount", 'othersShare', NEW."othersShare", 'currency', NEW."currency", 'exchangeRate', NEW."exchangeRate", 'amountInPen', NEW."amountInPen", 'expenseType', NEW."expenseType", 'paymentStatus', NEW."paymentStatus", 'personId', NEW."personId", 'categoryId', NEW."categoryId", 'paymentMethodId', NEW."paymentMethodId", 'installment', NEW."installment", 'paymentMonth', NEW."paymentMonth", 'paymentYear', NEW."paymentYear", 'processDate', NEW."processDate", 'notes', NEW."notes", 'originDraftId', NEW."originDraftId", 'draftId', NEW."draftId", 'createdAt', NEW."createdAt", 'updatedAt', NEW."updatedAt", 'importKey', NEW."importKey", 'userId', NEW."userId", 'tripId', NEW."tripId"), COALESCE(c."source", 'cli'), c."actorId", c."batchId", NEW."userId", strftime('%Y-%m-%dT%H:%M:%f', 'now') || '+00:00'
  FROM (SELECT 1) LEFT JOIN "aud_context" c ON c."id" = 1
  WHERE COALESCE(c."source", 'cli') <> 'import';
END;

CREATE TRIGGER "aud_upd_exp_credit_card_expenses" AFTER UPDATE ON "exp_credit_card_expenses"
BEGIN
  INSERT INTO "aud_changes" ("id", "entity", "entityId", "action", "changes", "source", "actorId", "batchId", "userId", "createdAt")
  SELECT lower(hex(randomblob(12))), 'exp_credit_card_expenses', NEW."id", 'update', diff."changes", COALESCE(c."source", 'cli'), c."actorId", c."batchId", NEW."userId", strftime('%Y-%m-%dT%H:%M:%f', 'now') || '+00:00'
  FROM (SELECT json_group_object("k", json_array("o", "n")) AS "changes", COUNT(*) AS "total" FROM (
      SELECT 'id' AS "k", OLD."id" AS "o", NEW."id" AS "n"
      UNION ALL SELECT 'description', OLD."description", NEW."description"
      UNION ALL SELECT 'amount', OLD."amount", NEW."amount"
      UNION ALL SELECT 'othersShare', OLD."othersShare", NEW."othersShare"
      UNION ALL SELECT 'currency', OLD."currency", NEW."currency"
      UNION ALL SELECT 'exchangeRate', OLD."exchangeRate", NEW."exchangeRate"
      UNION ALL SELECT 'amountInPen', OLD."amountInPen", NEW."amountInPen"
      UNION ALL SELECT 'expenseType', OLD."expenseType", NEW."expenseType"
      UNION ALL SELECT 'paymentStatus', OLD."paymentStatus", NEW."paymentStatus"
      UNION ALL SELECT 'personId', OLD."personId", NEW."personId"
      UNION ALL SELECT 'categoryId', OLD."categoryId", NEW."categoryId"
      UNION ALL SELECT 'paymentMethodId', OLD."paymentMethodId", NEW."paymentMethodId"
      UNION ALL SELECT 'installment', OLD."installment", NEW."installment"
      UNION ALL SELECT 'paymentMonth', OLD."paymentMonth", NEW."paymentMonth"
      UNION ALL SELECT 'paymentYear', OLD."paymentYear", NEW."paymentYear"
      UNION ALL SELECT 'processDate', OLD."processDate", NEW."processDate"
      UNION ALL SELECT 'notes', OLD."notes", NEW."notes"
      UNION ALL SELECT 'originDraftId', OLD."originDraftId", NEW."originDraftId"
      UNION ALL SELECT 'draftId', OLD."draftId", NEW."draftId"
      UNION ALL SELECT 'createdAt', OLD."createdAt", NEW."createdAt"
      UNION ALL SELECT 'importKey', OLD."importKey", NEW."importKey"
      UNION ALL SELECT 'userId', OLD."userId", NEW."userId"
      UNION ALL SELECT 'tripId', OLD."tripId", NEW."tripId"
    ) WHERE "o" IS NOT "n") diff
  LEFT JOIN "aud_context" c ON c."id" = 1
  WHERE diff."total" > 0 AND COALESCE(c."source", 'cli') <> 'import';
END;

CREATE TRIGGER "aud_del_exp_credit_card_expenses" AFTER DELETE ON "exp_credit_card_expenses"
BEGIN
  INSERT INTO "aud_changes" ("id", "entity", "entityId", "action", "changes", "source", "actorId", "batchId", "userId", "createdAt")
  SELECT lower(hex(randomblob(12))), 'exp_credit_card_expenses', OLD."id", 'delete', json_object('id', OLD."id", 'description', OLD."description", 'amount', OLD."amount", 'othersShare', OLD."othersShare", 'currency', OLD."currency", 'exchangeRate', OLD."exchangeRate", 'amountInPen', OLD."amountInPen", 'expenseType', OLD."expenseType", 'paymentStatus', OLD."paymentStatus", 'personId', OLD."personId", 'categoryId', OLD."categoryId", 'paymentMethodId', OLD."paymentMethodId", 'installment', OLD."installment", 'paymentMonth', OLD."paymentMonth", 'paymentYear', OLD."paymentYear", 'processDate', OLD."processDate", 'notes', OLD."notes", 'originDraftId', OLD."originDraftId", 'draftId', OLD."draftId", 'createdAt', OLD."createdAt", 'updatedAt', OLD."updatedAt", 'importKey', OLD."importKey", 'userId', OLD."userId", 'tripId', OLD."tripId"), COALESCE(c."source", 'cli'), c."actorId", c."batchId", OLD."userId", strftime('%Y-%m-%dT%H:%M:%f', 'now') || '+00:00'
  FROM (SELECT 1) LEFT JOIN "aud_context" c ON c."id" = 1
  WHERE COALESCE(c."source", 'cli') <> 'import';
END;

CREATE TRIGGER "aud_ins_exp_recurring_expenses" AFTER INSERT ON "exp_recurring_expenses"
BEGIN
  INSERT INTO "aud_changes" ("id", "entity", "entityId", "action", "changes", "source", "actorId", "batchId", "userId", "createdAt")
  SELECT lower(hex(randomblob(12))), 'exp_recurring_expenses', NEW."id", 'create', json_object('id', NEW."id", 'description', NEW."description", 'amount', NEW."amount", 'currency', NEW."currency", 'targetType', NEW."targetType", 'expenseType', NEW."expenseType", 'personId', NEW."personId", 'categoryId', NEW."categoryId", 'paymentMethodId', NEW."paymentMethodId", 'dayOfMonth', NEW."dayOfMonth", 'isActive', NEW."isActive", 'lastGeneratedAt', NEW."lastGeneratedAt", 'createdAt', NEW."createdAt", 'updatedAt', NEW."updatedAt", 'kind', NEW."kind", 'period', NEW."period", 'supplyNumber', NEW."supplyNumber", 'sharedWith', NEW."sharedWith", 'userId', NEW."userId"), COALESCE(c."source", 'cli'), c."actorId", c."batchId", NEW."userId", strftime('%Y-%m-%dT%H:%M:%f', 'now') || '+00:00'
  FROM (SELECT 1) LEFT JOIN "aud_context" c ON c."id" = 1
  WHERE COALESCE(c."source", 'cli') <> 'import';
END;

CREATE TRIGGER "aud_upd_exp_recurring_expenses" AFTER UPDATE ON "exp_recurring_expenses"
BEGIN
  INSERT INTO "aud_changes" ("id", "entity", "entityId", "action", "changes", "source", "actorId", "batchId", "userId", "createdAt")
  SELECT lower(hex(randomblob(12))), 'exp_recurring_expenses', NEW."id", 'update', diff."changes", COALESCE(c."source", 'cli'), c."actorId", c."batchId", NEW."userId", strftime('%Y-%m-%dT%H:%M:%f', 'now') || '+00:00'
  FROM (SELECT json_group_object("k", json_array("o", "n")) AS "changes", COUNT(*) AS "total" FROM (
      SELECT 'id' AS "k", OLD."id" AS "o", NEW."id" AS "n"
      UNION ALL SELECT 'description', OLD."description", NEW."description"
      UNION ALL SELECT 'amount', OLD."amount", NEW."amount"
      UNION ALL SELECT 'currency', OLD."currency", NEW."currency"
      UNION ALL SELECT 'targetType', OLD."targetType", NEW."targetType"
      UNION ALL SELECT 'expenseType', OLD."expenseType", NEW."expenseType"
      UNION ALL SELECT 'personId', OLD."personId", NEW."personId"
      UNION ALL SELECT 'categoryId', OLD."categoryId", NEW."categoryId"
      UNION ALL SELECT 'paymentMethodId', OLD."paymentMethodId", NEW."paymentMethodId"
      UNION ALL SELECT 'dayOfMonth', OLD."dayOfMonth", NEW."dayOfMonth"
      UNION ALL SELECT 'isActive', OLD."isActive", NEW."isActive"
      UNION ALL SELECT 'lastGeneratedAt', OLD."lastGeneratedAt", NEW."lastGeneratedAt"
      UNION ALL SELECT 'createdAt', OLD."createdAt", NEW."createdAt"
      UNION ALL SELECT 'kind', OLD."kind", NEW."kind"
      UNION ALL SELECT 'period', OLD."period", NEW."period"
      UNION ALL SELECT 'supplyNumber', OLD."supplyNumber", NEW."supplyNumber"
      UNION ALL SELECT 'sharedWith', OLD."sharedWith", NEW."sharedWith"
      UNION ALL SELECT 'userId', OLD."userId", NEW."userId"
    ) WHERE "o" IS NOT "n") diff
  LEFT JOIN "aud_context" c ON c."id" = 1
  WHERE diff."total" > 0 AND COALESCE(c."source", 'cli') <> 'import';
END;

CREATE TRIGGER "aud_del_exp_recurring_expenses" AFTER DELETE ON "exp_recurring_expenses"
BEGIN
  INSERT INTO "aud_changes" ("id", "entity", "entityId", "action", "changes", "source", "actorId", "batchId", "userId", "createdAt")
  SELECT lower(hex(randomblob(12))), 'exp_recurring_expenses', OLD."id", 'delete', json_object('id', OLD."id", 'description', OLD."description", 'amount', OLD."amount", 'currency', OLD."currency", 'targetType', OLD."targetType", 'expenseType', OLD."expenseType", 'personId', OLD."personId", 'categoryId', OLD."categoryId", 'paymentMethodId', OLD."paymentMethodId", 'dayOfMonth', OLD."dayOfMonth", 'isActive', OLD."isActive", 'lastGeneratedAt', OLD."lastGeneratedAt", 'createdAt', OLD."createdAt", 'updatedAt', OLD."updatedAt", 'kind', OLD."kind", 'period', OLD."period", 'supplyNumber', OLD."supplyNumber", 'sharedWith', OLD."sharedWith", 'userId', OLD."userId"), COALESCE(c."source", 'cli'), c."actorId", c."batchId", OLD."userId", strftime('%Y-%m-%dT%H:%M:%f', 'now') || '+00:00'
  FROM (SELECT 1) LEFT JOIN "aud_context" c ON c."id" = 1
  WHERE COALESCE(c."source", 'cli') <> 'import';
END;

CREATE TRIGGER "aud_ins_exp_debts" AFTER INSERT ON "exp_debts"
BEGIN
  INSERT INTO "aud_changes" ("id", "entity", "entityId", "action", "changes", "source", "actorId", "batchId", "userId", "createdAt")
  SELECT lower(hex(randomblob(12))), 'exp_debts', NEW."id", 'create', json_object('id', NEW."id", 'direction', NEW."direction", 'description', NEW."description", 'amount', NEW."amount", 'currency', NEW."currency", 'exchangeRate', NEW."exchangeRate", 'amountInPen', NEW."amountInPen", 'installment', NEW."installment", 'paymentMonth', NEW."paymentMonth", 'paymentYear', NEW."paymentYear", 'dueDate', NEW."dueDate", 'status', NEW."status", 'paidAmount', NEW."paidAmount", 'paidDate', NEW."paidDate", 'personId', NEW."personId", 'notes', NEW."notes", 'draftId', NEW."draftId", 'createdAt', NEW."createdAt", 'updatedAt', NEW."updatedAt", 'originDraftId', NEW."originDraftId", 'importKey', NEW."importKey", 'paymentMethodId', NEW."paymentMethodId", 'userId', NEW."userId"), COALESCE(c."source", 'cli'), c."actorId", c."batchId", NEW."userId", strftime('%Y-%m-%dT%H:%M:%f', 'now') || '+00:00'
  FROM (SELECT 1) LEFT JOIN "aud_context" c ON c."id" = 1
  WHERE COALESCE(c."source", 'cli') <> 'import';
END;

CREATE TRIGGER "aud_upd_exp_debts" AFTER UPDATE ON "exp_debts"
BEGIN
  INSERT INTO "aud_changes" ("id", "entity", "entityId", "action", "changes", "source", "actorId", "batchId", "userId", "createdAt")
  SELECT lower(hex(randomblob(12))), 'exp_debts', NEW."id", 'update', diff."changes", COALESCE(c."source", 'cli'), c."actorId", c."batchId", NEW."userId", strftime('%Y-%m-%dT%H:%M:%f', 'now') || '+00:00'
  FROM (SELECT json_group_object("k", json_array("o", "n")) AS "changes", COUNT(*) AS "total" FROM (
      SELECT 'id' AS "k", OLD."id" AS "o", NEW."id" AS "n"
      UNION ALL SELECT 'direction', OLD."direction", NEW."direction"
      UNION ALL SELECT 'description', OLD."description", NEW."description"
      UNION ALL SELECT 'amount', OLD."amount", NEW."amount"
      UNION ALL SELECT 'currency', OLD."currency", NEW."currency"
      UNION ALL SELECT 'exchangeRate', OLD."exchangeRate", NEW."exchangeRate"
      UNION ALL SELECT 'amountInPen', OLD."amountInPen", NEW."amountInPen"
      UNION ALL SELECT 'installment', OLD."installment", NEW."installment"
      UNION ALL SELECT 'paymentMonth', OLD."paymentMonth", NEW."paymentMonth"
      UNION ALL SELECT 'paymentYear', OLD."paymentYear", NEW."paymentYear"
      UNION ALL SELECT 'dueDate', OLD."dueDate", NEW."dueDate"
      UNION ALL SELECT 'status', OLD."status", NEW."status"
      UNION ALL SELECT 'paidAmount', OLD."paidAmount", NEW."paidAmount"
      UNION ALL SELECT 'paidDate', OLD."paidDate", NEW."paidDate"
      UNION ALL SELECT 'personId', OLD."personId", NEW."personId"
      UNION ALL SELECT 'notes', OLD."notes", NEW."notes"
      UNION ALL SELECT 'draftId', OLD."draftId", NEW."draftId"
      UNION ALL SELECT 'createdAt', OLD."createdAt", NEW."createdAt"
      UNION ALL SELECT 'originDraftId', OLD."originDraftId", NEW."originDraftId"
      UNION ALL SELECT 'importKey', OLD."importKey", NEW."importKey"
      UNION ALL SELECT 'paymentMethodId', OLD."paymentMethodId", NEW."paymentMethodId"
      UNION ALL SELECT 'userId', OLD."userId", NEW."userId"
    ) WHERE "o" IS NOT "n") diff
  LEFT JOIN "aud_context" c ON c."id" = 1
  WHERE diff."total" > 0 AND COALESCE(c."source", 'cli') <> 'import';
END;

CREATE TRIGGER "aud_del_exp_debts" AFTER DELETE ON "exp_debts"
BEGIN
  INSERT INTO "aud_changes" ("id", "entity", "entityId", "action", "changes", "source", "actorId", "batchId", "userId", "createdAt")
  SELECT lower(hex(randomblob(12))), 'exp_debts', OLD."id", 'delete', json_object('id', OLD."id", 'direction', OLD."direction", 'description', OLD."description", 'amount', OLD."amount", 'currency', OLD."currency", 'exchangeRate', OLD."exchangeRate", 'amountInPen', OLD."amountInPen", 'installment', OLD."installment", 'paymentMonth', OLD."paymentMonth", 'paymentYear', OLD."paymentYear", 'dueDate', OLD."dueDate", 'status', OLD."status", 'paidAmount', OLD."paidAmount", 'paidDate', OLD."paidDate", 'personId', OLD."personId", 'notes', OLD."notes", 'draftId', OLD."draftId", 'createdAt', OLD."createdAt", 'updatedAt', OLD."updatedAt", 'originDraftId', OLD."originDraftId", 'importKey', OLD."importKey", 'paymentMethodId', OLD."paymentMethodId", 'userId', OLD."userId"), COALESCE(c."source", 'cli'), c."actorId", c."batchId", OLD."userId", strftime('%Y-%m-%dT%H:%M:%f', 'now') || '+00:00'
  FROM (SELECT 1) LEFT JOIN "aud_context" c ON c."id" = 1
  WHERE COALESCE(c."source", 'cli') <> 'import';
END;

CREATE TRIGGER "aud_ins_exp_debt_payments" AFTER INSERT ON "exp_debt_payments"
BEGIN
  INSERT INTO "aud_changes" ("id", "entity", "entityId", "action", "changes", "source", "actorId", "batchId", "userId", "createdAt")
  SELECT lower(hex(randomblob(12))), 'exp_debt_payments', NEW."id", 'create', json_object('id', NEW."id", 'debtId', NEW."debtId", 'amount', NEW."amount", 'paidAt', NEW."paidAt", 'paymentMethodId', NEW."paymentMethodId", 'batchId', NEW."batchId", 'confirmedAt', NEW."confirmedAt", 'notes', NEW."notes", 'createdAt', NEW."createdAt", 'kind', NEW."kind", 'userId', NEW."userId"), COALESCE(c."source", 'cli'), c."actorId", c."batchId", NEW."userId", strftime('%Y-%m-%dT%H:%M:%f', 'now') || '+00:00'
  FROM (SELECT 1) LEFT JOIN "aud_context" c ON c."id" = 1
  WHERE COALESCE(c."source", 'cli') <> 'import';
END;

CREATE TRIGGER "aud_upd_exp_debt_payments" AFTER UPDATE ON "exp_debt_payments"
BEGIN
  INSERT INTO "aud_changes" ("id", "entity", "entityId", "action", "changes", "source", "actorId", "batchId", "userId", "createdAt")
  SELECT lower(hex(randomblob(12))), 'exp_debt_payments', NEW."id", 'update', diff."changes", COALESCE(c."source", 'cli'), c."actorId", c."batchId", NEW."userId", strftime('%Y-%m-%dT%H:%M:%f', 'now') || '+00:00'
  FROM (SELECT json_group_object("k", json_array("o", "n")) AS "changes", COUNT(*) AS "total" FROM (
      SELECT 'id' AS "k", OLD."id" AS "o", NEW."id" AS "n"
      UNION ALL SELECT 'debtId', OLD."debtId", NEW."debtId"
      UNION ALL SELECT 'amount', OLD."amount", NEW."amount"
      UNION ALL SELECT 'paidAt', OLD."paidAt", NEW."paidAt"
      UNION ALL SELECT 'paymentMethodId', OLD."paymentMethodId", NEW."paymentMethodId"
      UNION ALL SELECT 'batchId', OLD."batchId", NEW."batchId"
      UNION ALL SELECT 'confirmedAt', OLD."confirmedAt", NEW."confirmedAt"
      UNION ALL SELECT 'notes', OLD."notes", NEW."notes"
      UNION ALL SELECT 'createdAt', OLD."createdAt", NEW."createdAt"
      UNION ALL SELECT 'kind', OLD."kind", NEW."kind"
      UNION ALL SELECT 'userId', OLD."userId", NEW."userId"
    ) WHERE "o" IS NOT "n") diff
  LEFT JOIN "aud_context" c ON c."id" = 1
  WHERE diff."total" > 0 AND COALESCE(c."source", 'cli') <> 'import';
END;

CREATE TRIGGER "aud_del_exp_debt_payments" AFTER DELETE ON "exp_debt_payments"
BEGIN
  INSERT INTO "aud_changes" ("id", "entity", "entityId", "action", "changes", "source", "actorId", "batchId", "userId", "createdAt")
  SELECT lower(hex(randomblob(12))), 'exp_debt_payments', OLD."id", 'delete', json_object('id', OLD."id", 'debtId', OLD."debtId", 'amount', OLD."amount", 'paidAt', OLD."paidAt", 'paymentMethodId', OLD."paymentMethodId", 'batchId', OLD."batchId", 'confirmedAt', OLD."confirmedAt", 'notes', OLD."notes", 'createdAt', OLD."createdAt", 'kind', OLD."kind", 'userId', OLD."userId"), COALESCE(c."source", 'cli'), c."actorId", c."batchId", OLD."userId", strftime('%Y-%m-%dT%H:%M:%f', 'now') || '+00:00'
  FROM (SELECT 1) LEFT JOIN "aud_context" c ON c."id" = 1
  WHERE COALESCE(c."source", 'cli') <> 'import';
END;

CREATE TRIGGER "aud_ins_exp_commitments" AFTER INSERT ON "exp_commitments"
BEGIN
  INSERT INTO "aud_changes" ("id", "entity", "entityId", "action", "changes", "source", "actorId", "batchId", "userId", "createdAt")
  SELECT lower(hex(randomblob(12))), 'exp_commitments', NEW."id", 'create', json_object('id', NEW."id", 'name', NEW."name", 'kind', NEW."kind", 'subtype', NEW."subtype", 'entity', NEW."entity", 'currency', NEW."currency", 'totalAmount', NEW."totalAmount", 'installmentCount', NEW."installmentCount", 'installmentAmount', NEW."installmentAmount", 'dueDay', NEW."dueDay", 'startMonth', NEW."startMonth", 'startYear', NEW."startYear", 'cancellationAmount', NEW."cancellationAmount", 'cancellationDate', NEW."cancellationDate", 'status', NEW."status", 'personId', NEW."personId", 'categoryId', NEW."categoryId", 'notes', NEW."notes", 'createdAt', NEW."createdAt", 'updatedAt', NEW."updatedAt", 'userId', NEW."userId"), COALESCE(c."source", 'cli'), c."actorId", c."batchId", NEW."userId", strftime('%Y-%m-%dT%H:%M:%f', 'now') || '+00:00'
  FROM (SELECT 1) LEFT JOIN "aud_context" c ON c."id" = 1
  WHERE COALESCE(c."source", 'cli') <> 'import';
END;

CREATE TRIGGER "aud_upd_exp_commitments" AFTER UPDATE ON "exp_commitments"
BEGIN
  INSERT INTO "aud_changes" ("id", "entity", "entityId", "action", "changes", "source", "actorId", "batchId", "userId", "createdAt")
  SELECT lower(hex(randomblob(12))), 'exp_commitments', NEW."id", 'update', diff."changes", COALESCE(c."source", 'cli'), c."actorId", c."batchId", NEW."userId", strftime('%Y-%m-%dT%H:%M:%f', 'now') || '+00:00'
  FROM (SELECT json_group_object("k", json_array("o", "n")) AS "changes", COUNT(*) AS "total" FROM (
      SELECT 'id' AS "k", OLD."id" AS "o", NEW."id" AS "n"
      UNION ALL SELECT 'name', OLD."name", NEW."name"
      UNION ALL SELECT 'kind', OLD."kind", NEW."kind"
      UNION ALL SELECT 'subtype', OLD."subtype", NEW."subtype"
      UNION ALL SELECT 'entity', OLD."entity", NEW."entity"
      UNION ALL SELECT 'currency', OLD."currency", NEW."currency"
      UNION ALL SELECT 'totalAmount', OLD."totalAmount", NEW."totalAmount"
      UNION ALL SELECT 'installmentCount', OLD."installmentCount", NEW."installmentCount"
      UNION ALL SELECT 'installmentAmount', OLD."installmentAmount", NEW."installmentAmount"
      UNION ALL SELECT 'dueDay', OLD."dueDay", NEW."dueDay"
      UNION ALL SELECT 'startMonth', OLD."startMonth", NEW."startMonth"
      UNION ALL SELECT 'startYear', OLD."startYear", NEW."startYear"
      UNION ALL SELECT 'cancellationAmount', OLD."cancellationAmount", NEW."cancellationAmount"
      UNION ALL SELECT 'cancellationDate', OLD."cancellationDate", NEW."cancellationDate"
      UNION ALL SELECT 'status', OLD."status", NEW."status"
      UNION ALL SELECT 'personId', OLD."personId", NEW."personId"
      UNION ALL SELECT 'categoryId', OLD."categoryId", NEW."categoryId"
      UNION ALL SELECT 'notes', OLD."notes", NEW."notes"
      UNION ALL SELECT 'createdAt', OLD."createdAt", NEW."createdAt"
      UNION ALL SELECT 'userId', OLD."userId", NEW."userId"
    ) WHERE "o" IS NOT "n") diff
  LEFT JOIN "aud_context" c ON c."id" = 1
  WHERE diff."total" > 0 AND COALESCE(c."source", 'cli') <> 'import';
END;

CREATE TRIGGER "aud_del_exp_commitments" AFTER DELETE ON "exp_commitments"
BEGIN
  INSERT INTO "aud_changes" ("id", "entity", "entityId", "action", "changes", "source", "actorId", "batchId", "userId", "createdAt")
  SELECT lower(hex(randomblob(12))), 'exp_commitments', OLD."id", 'delete', json_object('id', OLD."id", 'name', OLD."name", 'kind', OLD."kind", 'subtype', OLD."subtype", 'entity', OLD."entity", 'currency', OLD."currency", 'totalAmount', OLD."totalAmount", 'installmentCount', OLD."installmentCount", 'installmentAmount', OLD."installmentAmount", 'dueDay', OLD."dueDay", 'startMonth', OLD."startMonth", 'startYear', OLD."startYear", 'cancellationAmount', OLD."cancellationAmount", 'cancellationDate', OLD."cancellationDate", 'status', OLD."status", 'personId', OLD."personId", 'categoryId', OLD."categoryId", 'notes', OLD."notes", 'createdAt', OLD."createdAt", 'updatedAt', OLD."updatedAt", 'userId', OLD."userId"), COALESCE(c."source", 'cli'), c."actorId", c."batchId", OLD."userId", strftime('%Y-%m-%dT%H:%M:%f', 'now') || '+00:00'
  FROM (SELECT 1) LEFT JOIN "aud_context" c ON c."id" = 1
  WHERE COALESCE(c."source", 'cli') <> 'import';
END;

CREATE TRIGGER "aud_ins_exp_contributions" AFTER INSERT ON "exp_contributions"
BEGIN
  INSERT INTO "aud_changes" ("id", "entity", "entityId", "action", "changes", "source", "actorId", "batchId", "userId", "createdAt")
  SELECT lower(hex(randomblob(12))), 'exp_contributions', NEW."id", 'create', json_object('id', NEW."id", 'commitmentId', NEW."commitmentId", 'date', NEW."date", 'amount', NEW."amount", 'currency', NEW."currency", 'quantity', NEW."quantity", 'unit', NEW."unit", 'notes', NEW."notes", 'createdAt', NEW."createdAt", 'updatedAt', NEW."updatedAt", 'userId', NEW."userId"), COALESCE(c."source", 'cli'), c."actorId", c."batchId", NEW."userId", strftime('%Y-%m-%dT%H:%M:%f', 'now') || '+00:00'
  FROM (SELECT 1) LEFT JOIN "aud_context" c ON c."id" = 1
  WHERE COALESCE(c."source", 'cli') <> 'import';
END;

CREATE TRIGGER "aud_upd_exp_contributions" AFTER UPDATE ON "exp_contributions"
BEGIN
  INSERT INTO "aud_changes" ("id", "entity", "entityId", "action", "changes", "source", "actorId", "batchId", "userId", "createdAt")
  SELECT lower(hex(randomblob(12))), 'exp_contributions', NEW."id", 'update', diff."changes", COALESCE(c."source", 'cli'), c."actorId", c."batchId", NEW."userId", strftime('%Y-%m-%dT%H:%M:%f', 'now') || '+00:00'
  FROM (SELECT json_group_object("k", json_array("o", "n")) AS "changes", COUNT(*) AS "total" FROM (
      SELECT 'id' AS "k", OLD."id" AS "o", NEW."id" AS "n"
      UNION ALL SELECT 'commitmentId', OLD."commitmentId", NEW."commitmentId"
      UNION ALL SELECT 'date', OLD."date", NEW."date"
      UNION ALL SELECT 'amount', OLD."amount", NEW."amount"
      UNION ALL SELECT 'currency', OLD."currency", NEW."currency"
      UNION ALL SELECT 'quantity', OLD."quantity", NEW."quantity"
      UNION ALL SELECT 'unit', OLD."unit", NEW."unit"
      UNION ALL SELECT 'notes', OLD."notes", NEW."notes"
      UNION ALL SELECT 'createdAt', OLD."createdAt", NEW."createdAt"
      UNION ALL SELECT 'userId', OLD."userId", NEW."userId"
    ) WHERE "o" IS NOT "n") diff
  LEFT JOIN "aud_context" c ON c."id" = 1
  WHERE diff."total" > 0 AND COALESCE(c."source", 'cli') <> 'import';
END;

CREATE TRIGGER "aud_del_exp_contributions" AFTER DELETE ON "exp_contributions"
BEGIN
  INSERT INTO "aud_changes" ("id", "entity", "entityId", "action", "changes", "source", "actorId", "batchId", "userId", "createdAt")
  SELECT lower(hex(randomblob(12))), 'exp_contributions', OLD."id", 'delete', json_object('id', OLD."id", 'commitmentId', OLD."commitmentId", 'date', OLD."date", 'amount', OLD."amount", 'currency', OLD."currency", 'quantity', OLD."quantity", 'unit', OLD."unit", 'notes', OLD."notes", 'createdAt', OLD."createdAt", 'updatedAt', OLD."updatedAt", 'userId', OLD."userId"), COALESCE(c."source", 'cli'), c."actorId", c."batchId", OLD."userId", strftime('%Y-%m-%dT%H:%M:%f', 'now') || '+00:00'
  FROM (SELECT 1) LEFT JOIN "aud_context" c ON c."id" = 1
  WHERE COALESCE(c."source", 'cli') <> 'import';
END;

CREATE TRIGGER "aud_ins_bud_monthly_budgets" AFTER INSERT ON "bud_monthly_budgets"
BEGIN
  INSERT INTO "aud_changes" ("id", "entity", "entityId", "action", "changes", "source", "actorId", "batchId", "userId", "createdAt")
  SELECT lower(hex(randomblob(12))), 'bud_monthly_budgets', NEW."id", 'create', json_object('id', NEW."id", 'month', NEW."month", 'year', NEW."year", 'salary', NEW."salary", 'limitPercent', NEW."limitPercent", 'createdAt', NEW."createdAt", 'updatedAt', NEW."updatedAt", 'userId', NEW."userId"), COALESCE(c."source", 'cli'), c."actorId", c."batchId", NEW."userId", strftime('%Y-%m-%dT%H:%M:%f', 'now') || '+00:00'
  FROM (SELECT 1) LEFT JOIN "aud_context" c ON c."id" = 1
  WHERE COALESCE(c."source", 'cli') <> 'import';
END;

CREATE TRIGGER "aud_upd_bud_monthly_budgets" AFTER UPDATE ON "bud_monthly_budgets"
BEGIN
  INSERT INTO "aud_changes" ("id", "entity", "entityId", "action", "changes", "source", "actorId", "batchId", "userId", "createdAt")
  SELECT lower(hex(randomblob(12))), 'bud_monthly_budgets', NEW."id", 'update', diff."changes", COALESCE(c."source", 'cli'), c."actorId", c."batchId", NEW."userId", strftime('%Y-%m-%dT%H:%M:%f', 'now') || '+00:00'
  FROM (SELECT json_group_object("k", json_array("o", "n")) AS "changes", COUNT(*) AS "total" FROM (
      SELECT 'id' AS "k", OLD."id" AS "o", NEW."id" AS "n"
      UNION ALL SELECT 'month', OLD."month", NEW."month"
      UNION ALL SELECT 'year', OLD."year", NEW."year"
      UNION ALL SELECT 'salary', OLD."salary", NEW."salary"
      UNION ALL SELECT 'limitPercent', OLD."limitPercent", NEW."limitPercent"
      UNION ALL SELECT 'createdAt', OLD."createdAt", NEW."createdAt"
      UNION ALL SELECT 'userId', OLD."userId", NEW."userId"
    ) WHERE "o" IS NOT "n") diff
  LEFT JOIN "aud_context" c ON c."id" = 1
  WHERE diff."total" > 0 AND COALESCE(c."source", 'cli') <> 'import';
END;

CREATE TRIGGER "aud_del_bud_monthly_budgets" AFTER DELETE ON "bud_monthly_budgets"
BEGIN
  INSERT INTO "aud_changes" ("id", "entity", "entityId", "action", "changes", "source", "actorId", "batchId", "userId", "createdAt")
  SELECT lower(hex(randomblob(12))), 'bud_monthly_budgets', OLD."id", 'delete', json_object('id', OLD."id", 'month', OLD."month", 'year', OLD."year", 'salary', OLD."salary", 'limitPercent', OLD."limitPercent", 'createdAt', OLD."createdAt", 'updatedAt', OLD."updatedAt", 'userId', OLD."userId"), COALESCE(c."source", 'cli'), c."actorId", c."batchId", OLD."userId", strftime('%Y-%m-%dT%H:%M:%f', 'now') || '+00:00'
  FROM (SELECT 1) LEFT JOIN "aud_context" c ON c."id" = 1
  WHERE COALESCE(c."source", 'cli') <> 'import';
END;

CREATE TRIGGER "aud_ins_bud_budget_groups" AFTER INSERT ON "bud_budget_groups"
BEGIN
  INSERT INTO "aud_changes" ("id", "entity", "entityId", "action", "changes", "source", "actorId", "batchId", "userId", "createdAt")
  SELECT lower(hex(randomblob(12))), 'bud_budget_groups', NEW."id", 'create', json_object('id', NEW."id", 'name', NEW."name", 'emoji', NEW."emoji", 'percentage', NEW."percentage", 'order', NEW."order", 'createdAt', NEW."createdAt", 'updatedAt', NEW."updatedAt", 'userId', NEW."userId"), COALESCE(c."source", 'cli'), c."actorId", c."batchId", NEW."userId", strftime('%Y-%m-%dT%H:%M:%f', 'now') || '+00:00'
  FROM (SELECT 1) LEFT JOIN "aud_context" c ON c."id" = 1
  WHERE COALESCE(c."source", 'cli') <> 'import';
END;

CREATE TRIGGER "aud_upd_bud_budget_groups" AFTER UPDATE ON "bud_budget_groups"
BEGIN
  INSERT INTO "aud_changes" ("id", "entity", "entityId", "action", "changes", "source", "actorId", "batchId", "userId", "createdAt")
  SELECT lower(hex(randomblob(12))), 'bud_budget_groups', NEW."id", 'update', diff."changes", COALESCE(c."source", 'cli'), c."actorId", c."batchId", NEW."userId", strftime('%Y-%m-%dT%H:%M:%f', 'now') || '+00:00'
  FROM (SELECT json_group_object("k", json_array("o", "n")) AS "changes", COUNT(*) AS "total" FROM (
      SELECT 'id' AS "k", OLD."id" AS "o", NEW."id" AS "n"
      UNION ALL SELECT 'name', OLD."name", NEW."name"
      UNION ALL SELECT 'emoji', OLD."emoji", NEW."emoji"
      UNION ALL SELECT 'percentage', OLD."percentage", NEW."percentage"
      UNION ALL SELECT 'order', OLD."order", NEW."order"
      UNION ALL SELECT 'createdAt', OLD."createdAt", NEW."createdAt"
      UNION ALL SELECT 'userId', OLD."userId", NEW."userId"
    ) WHERE "o" IS NOT "n") diff
  LEFT JOIN "aud_context" c ON c."id" = 1
  WHERE diff."total" > 0 AND COALESCE(c."source", 'cli') <> 'import';
END;

CREATE TRIGGER "aud_del_bud_budget_groups" AFTER DELETE ON "bud_budget_groups"
BEGIN
  INSERT INTO "aud_changes" ("id", "entity", "entityId", "action", "changes", "source", "actorId", "batchId", "userId", "createdAt")
  SELECT lower(hex(randomblob(12))), 'bud_budget_groups', OLD."id", 'delete', json_object('id', OLD."id", 'name', OLD."name", 'emoji', OLD."emoji", 'percentage', OLD."percentage", 'order', OLD."order", 'createdAt', OLD."createdAt", 'updatedAt', OLD."updatedAt", 'userId', OLD."userId"), COALESCE(c."source", 'cli'), c."actorId", c."batchId", OLD."userId", strftime('%Y-%m-%dT%H:%M:%f', 'now') || '+00:00'
  FROM (SELECT 1) LEFT JOIN "aud_context" c ON c."id" = 1
  WHERE COALESCE(c."source", 'cli') <> 'import';
END;

CREATE TRIGGER "aud_ins_bud_category_budgets" AFTER INSERT ON "bud_category_budgets"
BEGIN
  INSERT INTO "aud_changes" ("id", "entity", "entityId", "action", "changes", "source", "actorId", "batchId", "userId", "createdAt")
  SELECT lower(hex(randomblob(12))), 'bud_category_budgets', NEW."id", 'create', json_object('id', NEW."id", 'categoryId', NEW."categoryId", 'monthlyLimit', NEW."monthlyLimit", 'alertThreshold', NEW."alertThreshold", 'month', NEW."month", 'year', NEW."year", 'createdAt', NEW."createdAt", 'updatedAt', NEW."updatedAt", 'userId', NEW."userId"), COALESCE(c."source", 'cli'), c."actorId", c."batchId", NEW."userId", strftime('%Y-%m-%dT%H:%M:%f', 'now') || '+00:00'
  FROM (SELECT 1) LEFT JOIN "aud_context" c ON c."id" = 1
  WHERE COALESCE(c."source", 'cli') <> 'import';
END;

CREATE TRIGGER "aud_upd_bud_category_budgets" AFTER UPDATE ON "bud_category_budgets"
BEGIN
  INSERT INTO "aud_changes" ("id", "entity", "entityId", "action", "changes", "source", "actorId", "batchId", "userId", "createdAt")
  SELECT lower(hex(randomblob(12))), 'bud_category_budgets', NEW."id", 'update', diff."changes", COALESCE(c."source", 'cli'), c."actorId", c."batchId", NEW."userId", strftime('%Y-%m-%dT%H:%M:%f', 'now') || '+00:00'
  FROM (SELECT json_group_object("k", json_array("o", "n")) AS "changes", COUNT(*) AS "total" FROM (
      SELECT 'id' AS "k", OLD."id" AS "o", NEW."id" AS "n"
      UNION ALL SELECT 'categoryId', OLD."categoryId", NEW."categoryId"
      UNION ALL SELECT 'monthlyLimit', OLD."monthlyLimit", NEW."monthlyLimit"
      UNION ALL SELECT 'alertThreshold', OLD."alertThreshold", NEW."alertThreshold"
      UNION ALL SELECT 'month', OLD."month", NEW."month"
      UNION ALL SELECT 'year', OLD."year", NEW."year"
      UNION ALL SELECT 'createdAt', OLD."createdAt", NEW."createdAt"
      UNION ALL SELECT 'userId', OLD."userId", NEW."userId"
    ) WHERE "o" IS NOT "n") diff
  LEFT JOIN "aud_context" c ON c."id" = 1
  WHERE diff."total" > 0 AND COALESCE(c."source", 'cli') <> 'import';
END;

CREATE TRIGGER "aud_del_bud_category_budgets" AFTER DELETE ON "bud_category_budgets"
BEGIN
  INSERT INTO "aud_changes" ("id", "entity", "entityId", "action", "changes", "source", "actorId", "batchId", "userId", "createdAt")
  SELECT lower(hex(randomblob(12))), 'bud_category_budgets', OLD."id", 'delete', json_object('id', OLD."id", 'categoryId', OLD."categoryId", 'monthlyLimit', OLD."monthlyLimit", 'alertThreshold', OLD."alertThreshold", 'month', OLD."month", 'year', OLD."year", 'createdAt', OLD."createdAt", 'updatedAt', OLD."updatedAt", 'userId', OLD."userId"), COALESCE(c."source", 'cli'), c."actorId", c."batchId", OLD."userId", strftime('%Y-%m-%dT%H:%M:%f', 'now') || '+00:00'
  FROM (SELECT 1) LEFT JOIN "aud_context" c ON c."id" = 1
  WHERE COALESCE(c."source", 'cli') <> 'import';
END;

CREATE TRIGGER "aud_ins_bud_incomes" AFTER INSERT ON "bud_incomes"
BEGIN
  INSERT INTO "aud_changes" ("id", "entity", "entityId", "action", "changes", "source", "actorId", "batchId", "userId", "createdAt")
  SELECT lower(hex(randomblob(12))), 'bud_incomes', NEW."id", 'create', json_object('id', NEW."id", 'description', NEW."description", 'amount', NEW."amount", 'currency', NEW."currency", 'receivedAt', NEW."receivedAt", 'month', NEW."month", 'year', NEW."year", 'notes', NEW."notes", 'createdAt', NEW."createdAt", 'updatedAt', NEW."updatedAt", 'userId', NEW."userId"), COALESCE(c."source", 'cli'), c."actorId", c."batchId", NEW."userId", strftime('%Y-%m-%dT%H:%M:%f', 'now') || '+00:00'
  FROM (SELECT 1) LEFT JOIN "aud_context" c ON c."id" = 1
  WHERE COALESCE(c."source", 'cli') <> 'import';
END;

CREATE TRIGGER "aud_upd_bud_incomes" AFTER UPDATE ON "bud_incomes"
BEGIN
  INSERT INTO "aud_changes" ("id", "entity", "entityId", "action", "changes", "source", "actorId", "batchId", "userId", "createdAt")
  SELECT lower(hex(randomblob(12))), 'bud_incomes', NEW."id", 'update', diff."changes", COALESCE(c."source", 'cli'), c."actorId", c."batchId", NEW."userId", strftime('%Y-%m-%dT%H:%M:%f', 'now') || '+00:00'
  FROM (SELECT json_group_object("k", json_array("o", "n")) AS "changes", COUNT(*) AS "total" FROM (
      SELECT 'id' AS "k", OLD."id" AS "o", NEW."id" AS "n"
      UNION ALL SELECT 'description', OLD."description", NEW."description"
      UNION ALL SELECT 'amount', OLD."amount", NEW."amount"
      UNION ALL SELECT 'currency', OLD."currency", NEW."currency"
      UNION ALL SELECT 'receivedAt', OLD."receivedAt", NEW."receivedAt"
      UNION ALL SELECT 'month', OLD."month", NEW."month"
      UNION ALL SELECT 'year', OLD."year", NEW."year"
      UNION ALL SELECT 'notes', OLD."notes", NEW."notes"
      UNION ALL SELECT 'createdAt', OLD."createdAt", NEW."createdAt"
      UNION ALL SELECT 'userId', OLD."userId", NEW."userId"
    ) WHERE "o" IS NOT "n") diff
  LEFT JOIN "aud_context" c ON c."id" = 1
  WHERE diff."total" > 0 AND COALESCE(c."source", 'cli') <> 'import';
END;

CREATE TRIGGER "aud_del_bud_incomes" AFTER DELETE ON "bud_incomes"
BEGIN
  INSERT INTO "aud_changes" ("id", "entity", "entityId", "action", "changes", "source", "actorId", "batchId", "userId", "createdAt")
  SELECT lower(hex(randomblob(12))), 'bud_incomes', OLD."id", 'delete', json_object('id', OLD."id", 'description', OLD."description", 'amount', OLD."amount", 'currency', OLD."currency", 'receivedAt', OLD."receivedAt", 'month', OLD."month", 'year', OLD."year", 'notes', OLD."notes", 'createdAt', OLD."createdAt", 'updatedAt', OLD."updatedAt", 'userId', OLD."userId"), COALESCE(c."source", 'cli'), c."actorId", c."batchId", OLD."userId", strftime('%Y-%m-%dT%H:%M:%f', 'now') || '+00:00'
  FROM (SELECT 1) LEFT JOIN "aud_context" c ON c."id" = 1
  WHERE COALESCE(c."source", 'cli') <> 'import';
END;

CREATE TRIGGER "aud_ins_bud_settings" AFTER INSERT ON "bud_settings"
BEGIN
  INSERT INTO "aud_changes" ("id", "entity", "entityId", "action", "changes", "source", "actorId", "batchId", "userId", "createdAt")
  SELECT lower(hex(randomblob(12))), 'bud_settings', NEW."id", 'create', json_object('id', NEW."id", 'userId', NEW."userId", 'recurringCount', NEW."recurringCount", 'platformsCount', NEW."platformsCount", 'updatedAt', NEW."updatedAt"), COALESCE(c."source", 'cli'), c."actorId", c."batchId", NEW."userId", strftime('%Y-%m-%dT%H:%M:%f', 'now') || '+00:00'
  FROM (SELECT 1) LEFT JOIN "aud_context" c ON c."id" = 1
  WHERE COALESCE(c."source", 'cli') <> 'import';
END;

CREATE TRIGGER "aud_upd_bud_settings" AFTER UPDATE ON "bud_settings"
BEGIN
  INSERT INTO "aud_changes" ("id", "entity", "entityId", "action", "changes", "source", "actorId", "batchId", "userId", "createdAt")
  SELECT lower(hex(randomblob(12))), 'bud_settings', NEW."id", 'update', diff."changes", COALESCE(c."source", 'cli'), c."actorId", c."batchId", NEW."userId", strftime('%Y-%m-%dT%H:%M:%f', 'now') || '+00:00'
  FROM (SELECT json_group_object("k", json_array("o", "n")) AS "changes", COUNT(*) AS "total" FROM (
      SELECT 'id' AS "k", OLD."id" AS "o", NEW."id" AS "n"
      UNION ALL SELECT 'userId', OLD."userId", NEW."userId"
      UNION ALL SELECT 'recurringCount', OLD."recurringCount", NEW."recurringCount"
      UNION ALL SELECT 'platformsCount', OLD."platformsCount", NEW."platformsCount"
    ) WHERE "o" IS NOT "n") diff
  LEFT JOIN "aud_context" c ON c."id" = 1
  WHERE diff."total" > 0 AND COALESCE(c."source", 'cli') <> 'import';
END;

CREATE TRIGGER "aud_del_bud_settings" AFTER DELETE ON "bud_settings"
BEGIN
  INSERT INTO "aud_changes" ("id", "entity", "entityId", "action", "changes", "source", "actorId", "batchId", "userId", "createdAt")
  SELECT lower(hex(randomblob(12))), 'bud_settings', OLD."id", 'delete', json_object('id', OLD."id", 'userId', OLD."userId", 'recurringCount', OLD."recurringCount", 'platformsCount', OLD."platformsCount", 'updatedAt', OLD."updatedAt"), COALESCE(c."source", 'cli'), c."actorId", c."batchId", OLD."userId", strftime('%Y-%m-%dT%H:%M:%f', 'now') || '+00:00'
  FROM (SELECT 1) LEFT JOIN "aud_context" c ON c."id" = 1
  WHERE COALESCE(c."source", 'cli') <> 'import';
END;

CREATE TRIGGER "aud_ins_cat_people" AFTER INSERT ON "cat_people"
BEGIN
  INSERT INTO "aud_changes" ("id", "entity", "entityId", "action", "changes", "source", "actorId", "batchId", "userId", "createdAt")
  SELECT lower(hex(randomblob(12))), 'cat_people', NEW."id", 'create', json_object('id', NEW."id", 'name', NEW."name", 'aliases', NEW."aliases", 'isActive', NEW."isActive", 'isDefault', NEW."isDefault", 'createdAt', NEW."createdAt", 'updatedAt', NEW."updatedAt", 'documentNumber', CASE WHEN NEW."documentNumber" IS NULL THEN NULL ELSE '•••' END, 'userId', NEW."userId"), COALESCE(c."source", 'cli'), c."actorId", c."batchId", NEW."userId", strftime('%Y-%m-%dT%H:%M:%f', 'now') || '+00:00'
  FROM (SELECT 1) LEFT JOIN "aud_context" c ON c."id" = 1
  WHERE COALESCE(c."source", 'cli') <> 'import';
END;

CREATE TRIGGER "aud_upd_cat_people" AFTER UPDATE ON "cat_people"
BEGIN
  INSERT INTO "aud_changes" ("id", "entity", "entityId", "action", "changes", "source", "actorId", "batchId", "userId", "createdAt")
  SELECT lower(hex(randomblob(12))), 'cat_people', NEW."id", 'update', diff."changes", COALESCE(c."source", 'cli'), c."actorId", c."batchId", NEW."userId", strftime('%Y-%m-%dT%H:%M:%f', 'now') || '+00:00'
  FROM (SELECT json_group_object("k", json_array(CASE WHEN "k" IN ('documentNumber') THEN CASE WHEN "o" IS NULL THEN NULL ELSE '•••' END ELSE "o" END, CASE WHEN "k" IN ('documentNumber') THEN CASE WHEN "n" IS NULL THEN NULL ELSE '•••' END ELSE "n" END)) AS "changes", COUNT(*) AS "total" FROM (
      SELECT 'id' AS "k", OLD."id" AS "o", NEW."id" AS "n"
      UNION ALL SELECT 'name', OLD."name", NEW."name"
      UNION ALL SELECT 'aliases', OLD."aliases", NEW."aliases"
      UNION ALL SELECT 'isActive', OLD."isActive", NEW."isActive"
      UNION ALL SELECT 'isDefault', OLD."isDefault", NEW."isDefault"
      UNION ALL SELECT 'createdAt', OLD."createdAt", NEW."createdAt"
      UNION ALL SELECT 'documentNumber', OLD."documentNumber", NEW."documentNumber"
      UNION ALL SELECT 'userId', OLD."userId", NEW."userId"
    ) WHERE "o" IS NOT "n") diff
  LEFT JOIN "aud_context" c ON c."id" = 1
  WHERE diff."total" > 0 AND COALESCE(c."source", 'cli') <> 'import';
END;

CREATE TRIGGER "aud_del_cat_people" AFTER DELETE ON "cat_people"
BEGIN
  INSERT INTO "aud_changes" ("id", "entity", "entityId", "action", "changes", "source", "actorId", "batchId", "userId", "createdAt")
  SELECT lower(hex(randomblob(12))), 'cat_people', OLD."id", 'delete', json_object('id', OLD."id", 'name', OLD."name", 'aliases', OLD."aliases", 'isActive', OLD."isActive", 'isDefault', OLD."isDefault", 'createdAt', OLD."createdAt", 'updatedAt', OLD."updatedAt", 'documentNumber', CASE WHEN OLD."documentNumber" IS NULL THEN NULL ELSE '•••' END, 'userId', OLD."userId"), COALESCE(c."source", 'cli'), c."actorId", c."batchId", OLD."userId", strftime('%Y-%m-%dT%H:%M:%f', 'now') || '+00:00'
  FROM (SELECT 1) LEFT JOIN "aud_context" c ON c."id" = 1
  WHERE COALESCE(c."source", 'cli') <> 'import';
END;

CREATE TRIGGER "aud_ins_cat_payment_methods" AFTER INSERT ON "cat_payment_methods"
BEGIN
  INSERT INTO "aud_changes" ("id", "entity", "entityId", "action", "changes", "source", "actorId", "batchId", "userId", "createdAt")
  SELECT lower(hex(randomblob(12))), 'cat_payment_methods', NEW."id", 'create', json_object('id', NEW."id", 'name', NEW."name", 'type', NEW."type", 'code', NEW."code", 'aliases', NEW."aliases", 'isActive', NEW."isActive", 'showInBot', NEW."showInBot", 'billingCloseDay', NEW."billingCloseDay", 'paymentDueDay', NEW."paymentDueDay", 'color', NEW."color", 'createdAt', NEW."createdAt", 'updatedAt', NEW."updatedAt", 'isPrimary', NEW."isPrimary", 'bank', NEW."bank", 'supportsAmortization', NEW."supportsAmortization", 'supportsCashback', NEW."supportsCashback", 'userId', NEW."userId"), COALESCE(c."source", 'cli'), c."actorId", c."batchId", NEW."userId", strftime('%Y-%m-%dT%H:%M:%f', 'now') || '+00:00'
  FROM (SELECT 1) LEFT JOIN "aud_context" c ON c."id" = 1
  WHERE COALESCE(c."source", 'cli') <> 'import';
END;

CREATE TRIGGER "aud_upd_cat_payment_methods" AFTER UPDATE ON "cat_payment_methods"
BEGIN
  INSERT INTO "aud_changes" ("id", "entity", "entityId", "action", "changes", "source", "actorId", "batchId", "userId", "createdAt")
  SELECT lower(hex(randomblob(12))), 'cat_payment_methods', NEW."id", 'update', diff."changes", COALESCE(c."source", 'cli'), c."actorId", c."batchId", NEW."userId", strftime('%Y-%m-%dT%H:%M:%f', 'now') || '+00:00'
  FROM (SELECT json_group_object("k", json_array("o", "n")) AS "changes", COUNT(*) AS "total" FROM (
      SELECT 'id' AS "k", OLD."id" AS "o", NEW."id" AS "n"
      UNION ALL SELECT 'name', OLD."name", NEW."name"
      UNION ALL SELECT 'type', OLD."type", NEW."type"
      UNION ALL SELECT 'code', OLD."code", NEW."code"
      UNION ALL SELECT 'aliases', OLD."aliases", NEW."aliases"
      UNION ALL SELECT 'isActive', OLD."isActive", NEW."isActive"
      UNION ALL SELECT 'showInBot', OLD."showInBot", NEW."showInBot"
      UNION ALL SELECT 'billingCloseDay', OLD."billingCloseDay", NEW."billingCloseDay"
      UNION ALL SELECT 'paymentDueDay', OLD."paymentDueDay", NEW."paymentDueDay"
      UNION ALL SELECT 'color', OLD."color", NEW."color"
      UNION ALL SELECT 'createdAt', OLD."createdAt", NEW."createdAt"
      UNION ALL SELECT 'isPrimary', OLD."isPrimary", NEW."isPrimary"
      UNION ALL SELECT 'bank', OLD."bank", NEW."bank"
      UNION ALL SELECT 'supportsAmortization', OLD."supportsAmortization", NEW."supportsAmortization"
      UNION ALL SELECT 'supportsCashback', OLD."supportsCashback", NEW."supportsCashback"
      UNION ALL SELECT 'userId', OLD."userId", NEW."userId"
    ) WHERE "o" IS NOT "n") diff
  LEFT JOIN "aud_context" c ON c."id" = 1
  WHERE diff."total" > 0 AND COALESCE(c."source", 'cli') <> 'import';
END;

CREATE TRIGGER "aud_del_cat_payment_methods" AFTER DELETE ON "cat_payment_methods"
BEGIN
  INSERT INTO "aud_changes" ("id", "entity", "entityId", "action", "changes", "source", "actorId", "batchId", "userId", "createdAt")
  SELECT lower(hex(randomblob(12))), 'cat_payment_methods', OLD."id", 'delete', json_object('id', OLD."id", 'name', OLD."name", 'type', OLD."type", 'code', OLD."code", 'aliases', OLD."aliases", 'isActive', OLD."isActive", 'showInBot', OLD."showInBot", 'billingCloseDay', OLD."billingCloseDay", 'paymentDueDay', OLD."paymentDueDay", 'color', OLD."color", 'createdAt', OLD."createdAt", 'updatedAt', OLD."updatedAt", 'isPrimary', OLD."isPrimary", 'bank', OLD."bank", 'supportsAmortization', OLD."supportsAmortization", 'supportsCashback', OLD."supportsCashback", 'userId', OLD."userId"), COALESCE(c."source", 'cli'), c."actorId", c."batchId", OLD."userId", strftime('%Y-%m-%dT%H:%M:%f', 'now') || '+00:00'
  FROM (SELECT 1) LEFT JOIN "aud_context" c ON c."id" = 1
  WHERE COALESCE(c."source", 'cli') <> 'import';
END;

CREATE TRIGGER "aud_ins_cat_card_holders" AFTER INSERT ON "cat_card_holders"
BEGIN
  INSERT INTO "aud_changes" ("id", "entity", "entityId", "action", "changes", "source", "actorId", "batchId", "userId", "createdAt")
  SELECT lower(hex(randomblob(12))), 'cat_card_holders', NEW."id", 'create', json_object('id', NEW."id", 'paymentMethodId', NEW."paymentMethodId", 'personId', NEW."personId", 'role', NEW."role", 'last4', NEW."last4", 'createdAt', NEW."createdAt", 'userId', NEW."userId"), COALESCE(c."source", 'cli'), c."actorId", c."batchId", NEW."userId", strftime('%Y-%m-%dT%H:%M:%f', 'now') || '+00:00'
  FROM (SELECT 1) LEFT JOIN "aud_context" c ON c."id" = 1
  WHERE COALESCE(c."source", 'cli') <> 'import';
END;

CREATE TRIGGER "aud_upd_cat_card_holders" AFTER UPDATE ON "cat_card_holders"
BEGIN
  INSERT INTO "aud_changes" ("id", "entity", "entityId", "action", "changes", "source", "actorId", "batchId", "userId", "createdAt")
  SELECT lower(hex(randomblob(12))), 'cat_card_holders', NEW."id", 'update', diff."changes", COALESCE(c."source", 'cli'), c."actorId", c."batchId", NEW."userId", strftime('%Y-%m-%dT%H:%M:%f', 'now') || '+00:00'
  FROM (SELECT json_group_object("k", json_array("o", "n")) AS "changes", COUNT(*) AS "total" FROM (
      SELECT 'id' AS "k", OLD."id" AS "o", NEW."id" AS "n"
      UNION ALL SELECT 'paymentMethodId', OLD."paymentMethodId", NEW."paymentMethodId"
      UNION ALL SELECT 'personId', OLD."personId", NEW."personId"
      UNION ALL SELECT 'role', OLD."role", NEW."role"
      UNION ALL SELECT 'last4', OLD."last4", NEW."last4"
      UNION ALL SELECT 'createdAt', OLD."createdAt", NEW."createdAt"
      UNION ALL SELECT 'userId', OLD."userId", NEW."userId"
    ) WHERE "o" IS NOT "n") diff
  LEFT JOIN "aud_context" c ON c."id" = 1
  WHERE diff."total" > 0 AND COALESCE(c."source", 'cli') <> 'import';
END;

CREATE TRIGGER "aud_del_cat_card_holders" AFTER DELETE ON "cat_card_holders"
BEGIN
  INSERT INTO "aud_changes" ("id", "entity", "entityId", "action", "changes", "source", "actorId", "batchId", "userId", "createdAt")
  SELECT lower(hex(randomblob(12))), 'cat_card_holders', OLD."id", 'delete', json_object('id', OLD."id", 'paymentMethodId', OLD."paymentMethodId", 'personId', OLD."personId", 'role', OLD."role", 'last4', OLD."last4", 'createdAt', OLD."createdAt", 'userId', OLD."userId"), COALESCE(c."source", 'cli'), c."actorId", c."batchId", OLD."userId", strftime('%Y-%m-%dT%H:%M:%f', 'now') || '+00:00'
  FROM (SELECT 1) LEFT JOIN "aud_context" c ON c."id" = 1
  WHERE COALESCE(c."source", 'cli') <> 'import';
END;

CREATE TRIGGER "aud_ins_cat_categories" AFTER INSERT ON "cat_categories"
BEGIN
  INSERT INTO "aud_changes" ("id", "entity", "entityId", "action", "changes", "source", "actorId", "batchId", "userId", "createdAt")
  SELECT lower(hex(randomblob(12))), 'cat_categories', NEW."id", 'create', json_object('id', NEW."id", 'name', NEW."name", 'color', NEW."color", 'icon', NEW."icon", 'isDefault', NEW."isDefault", 'budgetGroupId', NEW."budgetGroupId", 'createdAt', NEW."createdAt", 'updatedAt', NEW."updatedAt", 'userId', NEW."userId"), COALESCE(c."source", 'cli'), c."actorId", c."batchId", NEW."userId", strftime('%Y-%m-%dT%H:%M:%f', 'now') || '+00:00'
  FROM (SELECT 1) LEFT JOIN "aud_context" c ON c."id" = 1
  WHERE COALESCE(c."source", 'cli') <> 'import';
END;

CREATE TRIGGER "aud_upd_cat_categories" AFTER UPDATE ON "cat_categories"
BEGIN
  INSERT INTO "aud_changes" ("id", "entity", "entityId", "action", "changes", "source", "actorId", "batchId", "userId", "createdAt")
  SELECT lower(hex(randomblob(12))), 'cat_categories', NEW."id", 'update', diff."changes", COALESCE(c."source", 'cli'), c."actorId", c."batchId", NEW."userId", strftime('%Y-%m-%dT%H:%M:%f', 'now') || '+00:00'
  FROM (SELECT json_group_object("k", json_array("o", "n")) AS "changes", COUNT(*) AS "total" FROM (
      SELECT 'id' AS "k", OLD."id" AS "o", NEW."id" AS "n"
      UNION ALL SELECT 'name', OLD."name", NEW."name"
      UNION ALL SELECT 'color', OLD."color", NEW."color"
      UNION ALL SELECT 'icon', OLD."icon", NEW."icon"
      UNION ALL SELECT 'isDefault', OLD."isDefault", NEW."isDefault"
      UNION ALL SELECT 'budgetGroupId', OLD."budgetGroupId", NEW."budgetGroupId"
      UNION ALL SELECT 'createdAt', OLD."createdAt", NEW."createdAt"
      UNION ALL SELECT 'userId', OLD."userId", NEW."userId"
    ) WHERE "o" IS NOT "n") diff
  LEFT JOIN "aud_context" c ON c."id" = 1
  WHERE diff."total" > 0 AND COALESCE(c."source", 'cli') <> 'import';
END;

CREATE TRIGGER "aud_del_cat_categories" AFTER DELETE ON "cat_categories"
BEGIN
  INSERT INTO "aud_changes" ("id", "entity", "entityId", "action", "changes", "source", "actorId", "batchId", "userId", "createdAt")
  SELECT lower(hex(randomblob(12))), 'cat_categories', OLD."id", 'delete', json_object('id', OLD."id", 'name', OLD."name", 'color', OLD."color", 'icon', OLD."icon", 'isDefault', OLD."isDefault", 'budgetGroupId', OLD."budgetGroupId", 'createdAt', OLD."createdAt", 'updatedAt', OLD."updatedAt", 'userId', OLD."userId"), COALESCE(c."source", 'cli'), c."actorId", c."batchId", OLD."userId", strftime('%Y-%m-%dT%H:%M:%f', 'now') || '+00:00'
  FROM (SELECT 1) LEFT JOIN "aud_context" c ON c."id" = 1
  WHERE COALESCE(c."source", 'cli') <> 'import';
END;

CREATE TRIGGER "aud_ins_ntf_settings" AFTER INSERT ON "ntf_settings"
BEGIN
  INSERT INTO "aud_changes" ("id", "entity", "entityId", "action", "changes", "source", "actorId", "batchId", "userId", "createdAt")
  SELECT lower(hex(randomblob(12))), 'ntf_settings', NEW."kind", 'create', json_object('kind', NEW."kind", 'userId', NEW."userId", 'telegram', NEW."telegram", 'web', NEW."web", 'updatedAt', NEW."updatedAt"), COALESCE(c."source", 'cli'), c."actorId", c."batchId", NEW."userId", strftime('%Y-%m-%dT%H:%M:%f', 'now') || '+00:00'
  FROM (SELECT 1) LEFT JOIN "aud_context" c ON c."id" = 1
  WHERE COALESCE(c."source", 'cli') <> 'import';
END;

CREATE TRIGGER "aud_upd_ntf_settings" AFTER UPDATE ON "ntf_settings"
BEGIN
  INSERT INTO "aud_changes" ("id", "entity", "entityId", "action", "changes", "source", "actorId", "batchId", "userId", "createdAt")
  SELECT lower(hex(randomblob(12))), 'ntf_settings', NEW."kind", 'update', diff."changes", COALESCE(c."source", 'cli'), c."actorId", c."batchId", NEW."userId", strftime('%Y-%m-%dT%H:%M:%f', 'now') || '+00:00'
  FROM (SELECT json_group_object("k", json_array("o", "n")) AS "changes", COUNT(*) AS "total" FROM (
      SELECT 'kind' AS "k", OLD."kind" AS "o", NEW."kind" AS "n"
      UNION ALL SELECT 'userId', OLD."userId", NEW."userId"
      UNION ALL SELECT 'telegram', OLD."telegram", NEW."telegram"
      UNION ALL SELECT 'web', OLD."web", NEW."web"
    ) WHERE "o" IS NOT "n") diff
  LEFT JOIN "aud_context" c ON c."id" = 1
  WHERE diff."total" > 0 AND COALESCE(c."source", 'cli') <> 'import';
END;

CREATE TRIGGER "aud_del_ntf_settings" AFTER DELETE ON "ntf_settings"
BEGIN
  INSERT INTO "aud_changes" ("id", "entity", "entityId", "action", "changes", "source", "actorId", "batchId", "userId", "createdAt")
  SELECT lower(hex(randomblob(12))), 'ntf_settings', OLD."kind", 'delete', json_object('kind', OLD."kind", 'userId', OLD."userId", 'telegram', OLD."telegram", 'web', OLD."web", 'updatedAt', OLD."updatedAt"), COALESCE(c."source", 'cli'), c."actorId", c."batchId", OLD."userId", strftime('%Y-%m-%dT%H:%M:%f', 'now') || '+00:00'
  FROM (SELECT 1) LEFT JOIN "aud_context" c ON c."id" = 1
  WHERE COALESCE(c."source", 'cli') <> 'import';
END;
